name: course_booking_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_swiper: ^1.1.4
  dio: ^3.0.9
  provider: ^4.0.4
  flutter_easyrefresh: ^1.2.7
  fluro: ^1.5.2
  flutter_html: ^0.11.1
  date_format: ^1.0.8
  video_player: ^0.10.4
  chewie: 0.9.8+1
  flutter_webview_plugin: 0.3.10+1
  webview_flutter: 0.3.18+1
  image_gallery_saver: ^1.2.2
  permission_handler: ^4.3.0
  image_picker: 0.6.3+4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/banners/1.jpeg
    - assets/images/banners/2.jpeg
    - assets/images/banners/3.jpeg
    - assets/images/banners/4.jpeg
    - assets/images/banners/5.png
    - assets/images/loading/1.jpeg
    - assets/images/loading/2.jpeg
    - assets/images/avatar.jpeg
    - assets/images/dog.jpeg
    - assets/images/courses/1.png
    - assets/images/courses/2.png
    - assets/images/courses/3.png
    - assets/images/courses/4.png
    - assets/images/courses/5.png
    - assets/images/courses/6.png
    - assets/images/comment.png

    - assets/icons/me/medal.png
    - assets/icons/me/course.png
    - assets/icons/me/profile.png
    - assets/icons/me/situation.png
    - assets/icons/me/comment.png
    - assets/icons/me/grow.png
    - assets/icons/me/man.png
    - assets/icons/me/woman.png
    - assets/icons/location.png

    - assets/video/test.mp4

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
